In [5]:
import os
from matplotlib import pyplot as plt 
import numpy as np
from PIL import Image

root_dir = '../data/data_crop1024_shift512/'

img_dir = os.path.join(root_dir, 'train_images')
label_dir = os.path.join(root_dir, '1024-train-mask-mult')

img_path_list = os.listdir(img_dir)
label_path_list = os.listdir(label_dir)


In [6]:

for i in range(0, len(img_path_list)):
    img_path = os.path.join(img_dir, img_path_list[i])
    img = Image.open(img_path)
    
    if img.size != (1024, 1024):
        print(img_mask.size)


In [15]:
img_path

'../data/data_crop1024_shift512/train_images/Greenland26X_22W_Sentinel2_2019-07-31_25_r6__h22_w24.jpg'

In [16]:
label_path

'../data/data_crop1024_shift512/1024-train-mask-mult/Greenland26X_22W_Sentinel2_2019-08-25_29_r3__h6_w13_mask.jpg'

In [17]:
label = label.resize((256,256))

In [9]:
for i in range(0, len(label_path_list)):
    label_path = os.path.join(label_dir, label_path_list[i])
    label = Image.open(label_path)
    
    print(np.unique(label))

[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1

In [13]:
label_array = np.array(label)
label_array[label_array==2]=1

In [14]:
np.unique(label_array)

array([0, 1], dtype=uint8)