In [2]:
import os
from matplotlib import pyplot as plt 
import numpy as np
from PIL import Image

root_dir = '../data/data_crop1024_shift512/'

img_dir = os.path.join(root_dir, 'train_images')
label_dir = os.path.join(root_dir, 'train_mask')

img_path_list = os.listdir(img_dir)
label_path_list = os.listdir(label_dir)


In [3]:

for i in range(0, len(img_path_list)):
    img_path = os.path.join(img_dir, img_path_list[i])
    img = Image.open(img_path)
    
    if img.size != (1024, 1024):
        print(img_mask.size)


In [4]:
img_path

'../data/data_crop1024_shift512/train_images/Greenland26X_22W_Sentinel2_2019-07-31_25_r6__h22_w24.jpg'

In [8]:
negative_file_list = []
for i in range(0, len(label_path_list)):
    label_path = os.path.join(label_dir, label_path_list[i])
    label = Image.open(label_path)
    
    print(np.unique(label))
    if len(np.unique(label)) == 1: # only zero values
        negative_file_list.append(label_path_list[i])

[0]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[  0   1   2   3   4   5   6 248 249 250 251 252 253 254 255]
[0]
[  0   1   2   3   4   5   6 249 250 251 252 253 254 255]
[0]
[0]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[0]
[0]
[0]
[0]
[0]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[  0   1   2   3   4   5   7 248 250 251 252 253 254 255]
[0]
[0]
[0]
[0]
[  0   1   2   3   4   5 250 252 254 255]
[0]
[0]
[  0   1   2   3   4   5   6   7 249 250 251 252 253 254 255]
[0]
[  0   1   2   3   4   5   6   7 249 250 251 252 253 254 255]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[  0   1   2   3   4   5   6   7 248 249 250 251 252 253 254 255]
[  0   1   2  

In [9]:
len(negative_file_list)

5800

In [10]:
len(label_path_list)

7604

In [11]:
7604-5800

1804

In [13]:
label_array = np.array(label)
label_array[label_array==2]=1

In [14]:
np.unique(label_array)

array([0, 1], dtype=uint8)